const pieces = {
        towerR: {
            type:'tower',
            fired:false,
            position:''
        },
        towerL: {
            type:'tower',
            fired:false,
            position:''
        },
        horseR:{
            type:'horse',
            fired:false,
            position:''
        },
        horseL:{
            type:'horse',
            fired:false,
            position:''
        },
        bishopR:{
            type:'bishop',
            fired:false,
            position:''
        },
        bishopL:{
            type:'bishop',
            fired:false,
            position:''
        },
        king:{
            type:'king',
            fired:false,
            position:''
        },
        queen:{
            type:'queen',
            fired:false,
            position:''
        },
        pawn1:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn2:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn3:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn4:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn5:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn6:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn7:{
            type:'pawn',
            fired:false,
            position:''
        },
        pawn8:{
            type:'pawn',
            fired:false,
            position:''
        },
    }

export default pieces
